# Generated by Django 2.2.7 on 2019-11-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=256)),
                ('bairro', models.CharField(max_length=100)),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
            ],
        ),
    ]
