version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: project.dockerfile
    command: python src/manage.py runserver 0.0.0.0:3000
    volumes:
      - ./:/code
    ports:
      - "3000:3000"
    container_name: server
    networks: 
     - shared-network
    stdin_open: true
    tty: true

networks:
  shared-network:
    driver: bridge


