# Generated by Django 2.2.7 on 2019-11-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('infantil', 'Educação Infantil'), ('medio', 'Ensino Médio')], max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('estadual', 'Estadual'), ('federal', 'Federal'), ('municipal', 'Municipal'), ('particular', 'Particular')], max_length=100),
        ),
    ]
