# Generated by Django 2.2.7 on 2019-11-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='conveniada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='nro_entidade',
            field=models.BigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
