# Generated by Django 2.2.7 on 2019-11-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20191124_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='aee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='agua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='atividade_extracurricular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='biblioteca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='esgoto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='lab_ciencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='lab_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='merenda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='parque_infantil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='patio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='pne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='quadra',
            field=models.BooleanField(default=False),
        ),
    ]
