# Generated by Django 2.2.7 on 2019-11-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(default=0, max_length=280),
            preserve_default=False,
        ),
    ]
