# Generated by Django 2.2.7 on 2019-11-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20191124_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='tipo_pessoa',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
