# Generated by Django 2.2.7 on 2019-11-24 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20191124_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='absolute',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
